import { User } from "@/types/user";
import { Category } from "@/types/category";
import { Product } from "@/types/product";
import { CartItem } from "@/types/cart";
import { Order } from "@/types/order";
import { Notification } from "@/types/notification";

export const mockCustomerUser: User = {
  id: 1,
  name: "Alex Morgan",
  email: "alex@example.com",
  role: "customer",
  phone: "+1 (555) 234-5678",
  address: "742 Evergreen Terrace, Springfield",
  created_at: new Date().toISOString(),
};

export const mockAdminUser: User = {
  id: 2,
  name: "Admin Manager",
  email: "admin@ecommerce.com",
  role: "admin",
  phone: "+1 (555) 987-6543",
  address: "100 Corporate Plaza, Suite 400",
  created_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Flagship Electronics",
    slug: "electronics",
    description: "Cutting-edge smartphones, laptops, smart home gear, and wireless audio.",
    image: "/images/banners/hero-1.jpg",
    products_count: 12,
  },
  {
    id: 2,
    name: "Premium Audio",
    slug: "audio",
    description: "Studio-grade headphones, noise-cancelling earbuds, and spatial soundbars.",
    image: "/images/banners/hero-2.jpg",
    products_count: 8,
  },
  {
    id: 3,
    name: "Smart Wearables",
    slug: "wearables",
    description: "Next-gen fitness trackers, cellular smartwatches, and precision biometric rings.",
    image: "/images/banners/hero-1.jpg",
    products_count: 6,
  },
  {
    id: 4,
    name: "Workstation & Setup",
    slug: "workstation",
    description: "Ergonomic mechanical keyboards, 4K monitors, and minimalist desk accents.",
    image: "/images/banners/hero-2.jpg",
    products_count: 9,
  },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Aura Pro Wireless ANC Headphones",
    slug: "aura-pro-wireless-anc-headphones",
    description: "Industry-leading active noise cancellation with 40-hour battery life, custom 40mm beryllium drivers, multipoint bluetooth 5.3, and ultra-plush memory foam earpads.",
    price: 299.99,
    compare_price: 349.99,
    discount_percent: 14,
    stock: 24,
    is_active: 1,
    featured: 1,
    image: "/images/products/placeholder.png",
    category_id: 2,
    category: mockCategories[1],
    rating: 4.9,
    reviews_count: 128,
    reviews: [
      {
        id: 101,
        product_id: 1,
        user_id: 1,
        user: mockCustomerUser,
        rating: 5,
        comment: "The soundstage and clarity are incredible. ANC cuts down flight engine noise completely!",
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        id: 102,
        product_id: 1,
        user_id: 3,
        user: { id: 3, name: "Sarah Jenkins", email: "sarah@example.com" },
        rating: 5,
        comment: "Battery really lasts over 40 hours. Super comfortable during long work sessions.",
        created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Zenith X Ultra Smartwatch",
    slug: "zenith-x-ultra-smartwatch",
    description: "Titanium aerospace grade case with sapphire crystal glass, ECG sensor, GPS dual frequency tracking, and water resistant up to 100 meters.",
    price: 399.0,
    compare_price: 450.0,
    discount_percent: 11,
    stock: 18,
    is_active: 1,
    featured: 1,
    image: "/images/products/placeholder.png",
    category_id: 3,
    category: mockCategories[2],
    rating: 4.8,
    reviews_count: 94,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "NovaBook 16 M-Studio Laptop",
    slug: "novabook-16-m-studio-laptop",
    description: "Ultra-thin aluminum chassis featuring a 16-inch 120Hz Liquid Retina display, 32GB unified RAM, 1TB NVMe Gen4 SSD, and revolutionary thermal efficiency.",
    price: 1899.0,
    compare_price: 2099.0,
    discount_percent: 9,
    stock: 7,
    is_active: 1,
    featured: 1,
    image: "/images/products/placeholder.png",
    category_id: 1,
    category: mockCategories[0],
    rating: 4.95,
    reviews_count: 52,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Vanguard Wireless Mechanical Keyboard",
    slug: "vanguard-wireless-mechanical-keyboard",
    description: "Custom pre-lubed linear switches, hot-swappable PCB, CNC anodized aluminum plate, RGB per-key backlighting, and triple connectivity (2.4GHz, BT, USB-C).",
    price: 149.5,
    compare_price: 179.5,
    discount_percent: 17,
    stock: 45,
    is_active: 1,
    featured: 1,
    image: "/images/products/placeholder.png",
    category_id: 4,
    category: mockCategories[3],
    rating: 4.7,
    reviews_count: 73,
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Pulse Pods 2 True Wireless",
    slug: "pulse-pods-2-true-wireless",
    description: "Compact wireless earbuds with adaptive transparency mode, wireless Qi fast charging, 6-microphone beamforming for crystal calls, and IPX5 sweat resistance.",
    price: 129.99,
    compare_price: 159.99,
    discount_percent: 19,
    stock: 60,
    is_active: 1,
    featured: 0,
    image: "/images/products/placeholder.png",
    category_id: 2,
    category: mockCategories[1],
    rating: 4.6,
    reviews_count: 88,
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "ErgoFlow Curved 4K Monitor 34\"",
    slug: "ergoflow-curved-4k-monitor-34",
    description: "Ultrawide 3440x1440 resolution, 144Hz refresh rate, 99% DCI-P3 color gamut, USB-C 90W power delivery hub, and built-in KVM switch.",
    price: 649.0,
    compare_price: 749.0,
    discount_percent: 13,
    stock: 12,
    is_active: 1,
    featured: 1,
    image: "/images/products/placeholder.png",
    category_id: 4,
    category: mockCategories[3],
    rating: 4.85,
    reviews_count: 41,
    created_at: new Date().toISOString(),
  },
];

export const mockCartItems: CartItem[] = [
  {
    id: 1,
    product_id: 1,
    quantity: 1,
    price: 299.99,
    product: mockProducts[0],
  },
  {
    id: 2,
    product_id: 4,
    quantity: 1,
    price: 149.5,
    product: mockProducts[3],
  },
];

export const mockOrders: Order[] = [
  {
    id: 1001,
    order_number: "ORD-88231",
    user_id: 1,
    status: "processing",
    total_amount: 449.49,
    subtotal: 449.49,
    tax: 0,
    shipping_fee: 0,
    payment_method: "card",
    payment_status: "paid",
    shipping_name: "Alex Morgan",
    shipping_email: "alex@example.com",
    shipping_phone: "+1 (555) 234-5678",
    shipping_address: "742 Evergreen Terrace",
    shipping_city: "Springfield",
    shipping_postal_code: "97477",
    notes: "Please leave at front doorstep",
    items: [
      {
        id: 1,
        order_id: 1001,
        product_id: 1,
        quantity: 1,
        price: 299.99,
        product: mockProducts[0],
      },
      {
        id: 2,
        order_id: 1001,
        product_id: 4,
        quantity: 1,
        price: 149.5,
        product: mockProducts[3],
      },
    ],
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 1002,
    order_number: "ORD-76194",
    user_id: 1,
    status: "delivered",
    total_amount: 129.99,
    subtotal: 129.99,
    tax: 0,
    shipping_fee: 0,
    payment_method: "bkash",
    payment_status: "paid",
    shipping_name: "Alex Morgan",
    shipping_email: "alex@example.com",
    shipping_phone: "+1 (555) 234-5678",
    shipping_address: "742 Evergreen Terrace",
    shipping_city: "Springfield",
    shipping_postal_code: "97477",
    items: [
      {
        id: 3,
        order_id: 1002,
        product_id: 5,
        quantity: 1,
        price: 129.99,
        product: mockProducts[4],
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "order_status",
    title: "Order Processed",
    message: "Your order #ORD-88231 has been confirmed and is being packed for dispatch.",
    read_at: null,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "notif-2",
    type: "promotion",
    title: "Flash Sale Alert! ⚡",
    message: "Weekend Tech Blowout: Get up to 30% discount on all wireless mechanical accessories.",
    read_at: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "notif-3",
    type: "system",
    title: "Welcome to NovaStore",
    message: "Thank you for joining our community. Enjoy exclusive member perks and priority shipping.",
    read_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];
